sudo: false
dist: trusty
language: ruby
bundler_args: --without debug
before_script: bundle exec jekyll --version
script: bundle exec rake features_with_coveralls
rvm:
  - '2.6'
  - '2.5'
  - '2.4'
  - '2.3'
  - '2.2'
